CREATE TABLE "CANDIDATE"."BADGE" (
	"BADGE_NUMBER" NUMBER
	,"BADGE_STATUS" VARCHAR2(10)
	,"BADGE_EXPIRY_DATE" DATE
	,CONSTRAINT "BADGE_PK" PRIMARY KEY ("BADGE_NUMBER") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS" ENABLE
	) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE (INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS";

CREATE TABLE "CANDIDATE"."DEPARTMENT" (
	"DEPARTMENT_CODE" NUMBER
	,"DEPARTMENT_NAME" VARCHAR2(50)
	,CONSTRAINT "DEP_PK" PRIMARY KEY ("DEPARTMENT_CODE") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS" ENABLE
	) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE (INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS";

CREATE TABLE "CANDIDATE"."JOB_TITLE" (
	"JOB_TITLE_CODE" NUMBER
	,"JOB_TITLE_NAME" VARCHAR2(50)
	,"DEPARTMENT_CODE" NUMBER
	,CONSTRAINT "JOB_PK" PRIMARY KEY ("JOB_TITLE_CODE") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS" ENABLE
	,CONSTRAINT "DEP_FK" FOREIGN KEY ("DEPARTMENT_CODE") REFERENCES "CANDIDATE"."DEPARTMENT" ("DEPARTMENT_CODE") ENABLE
	) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE (INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS";

CREATE TABLE "CANDIDATE"."EMPLOYEE" (
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE
	,"FIRSTNAME" VARCHAR2(100)
	,"LASTNAME" VARCHAR2(100)
	,"BADGE_NUMBER" NUMBER
	,"COUNTRY_CODE" VARCHAR2(10)
	,"JOB_TITLE_CODE" NUMBER
	,"START_DATE" DATE
	,"LEAVE_DATE" DATE
	,CONSTRAINT "EMP_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS" ENABLE
	,CONSTRAINT "JOB_FK" FOREIGN KEY ("JOB_TITLE_CODE") REFERENCES "CANDIDATE"."JOB_TITLE" ("JOB_TITLE_CODE") ENABLE
	,CONSTRAINT "BADGE_FK" FOREIGN KEY ("BADGE_NUMBER") REFERENCES "CANDIDATE"."BADGE" ("BADGE_NUMBER") ENABLE
	) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE (INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS";
